config/routes.rb
Rails.application.routes.draw do
  root "cars#index"
  resources :cars, only: [:index, :new, :create] do
    collection do
      get "search"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/body.rb
class Body < ActiveHash::Base
  self.data = [
    { id: 1, name: 'セダン' },
    { id: 2, name: 'ミニバン' },
    { id: 3, name: 'SUV' },
    { id: 4, name: 'ハッチバック' },
    { id: 5, name: 'クーペ' },
    { id: 6, name: 'オープン' },
    { id: 7, name: '軽自動車' },
    { id: 8, name: 'その他' }
  ]

  include ActiveHash::Associations

  has_many :cars
end

app/models/car.rb
class Car < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :manufacturer
  belongs_to :body
  belongs_to :vehicle_type

  with_options presence: true do
    validates :name
    validates :price
    validates :grade
    validates :displacement
    validates :color
    validates :capacity
    validates :model_year
    validates :mileage
  end

end

app/models/color.rb
class Color < ActiveHash::Base
  self.data = [
    { color: '赤', name: '赤' },
    { color: '青', name: '青' },
    { color: '緑', name: '緑' },
    { color: '黄色', name: '黄色' },
    { color: '白', name: '白' },
    { color: '黒', name: '黒' },
    { color: 'シルバー', name: 'シルバー' },
    { color: 'ゴールド', name: 'ゴールド' }
  ]
end

app/models/manufacturer.rb
class Manufacturer < ActiveHash::Base
  self.data = [
    { id: 1, name: 'トヨタ' },
    { id: 2, name: '日産' },
    { id: 3, name: '三菱' },
    { id: 4, name: 'マツダ' },
    { id: 5, name: 'ホンダ' },
    { id: 6, name: 'スバル' },
    { id: 7, name: 'ダイハツ' },
    { id: 8, name: 'スズキ' },
    { id: 9, name: '外国車' },
    { id: 10, name: 'その他' }
  ]

  include ActiveHash::Associations

  has_many :cars
end

app/models/mileage.rb
class Mileage < ActiveHash::Base
  self.data = [
    { mileage: 5000, name: '5,000km' },
    { mileage: 10000, name: '1万km' },
    { mileage: 20000, name: '2万km' },
    { mileage: 30000, name: '3万km' },
    { mileage: 40000, name: '4万km' },
    { mileage: 50000, name: '5万km' },
    { mileage: 60000, name: '6万km' },
    { mileage: 70000, name: '7万km' },
    { mileage: 80000, name: '8万km' },
    { mileage: 90000, name: '9万km' },
    { mileage: 100000, name: '10万km' },
    { mileage: 110000, name: '11万km' },
    { mileage: 120000, name: '12万km' },
    { mileage: 130000, name: '13万km' },
    { mileage: 140000, name: '14万km' },
    { mileage: 150000, name: '15万km' },
    { mileage: 160000, name: '16万km' },
    { mileage: 170000, name: '17万km' },
    { mileage: 180000, name: '18万km' },
    { mileage: 190000, name: '19万km' },
    { mileage: 200000, name: '20万km' }
  ]
end

app/models/price.rb
class Price < ActiveHash::Base
  self.data = [
    { price: 1, name: "1万円" },
    { price: 2, name: "2万円" },
    { price: 3, name: "3万円" },
    { price: 4, name: "4万円" },
    { price: 5, name: "5万円" },
    { price: 6, name: "6万円" },
    { price: 7, name: "7万円" },
    { price: 8, name: "8万円" },
    { price: 9, name: "9万円" },
    { price: 10, name: "10万円" },
    { price: 11, name: "11万円" },
    { price: 12, name: "12万円" },
    { price: 13, name: "13万円" },
    { price: 14, name: "14万円" },
    { price: 15, name: "15万円" },
    { price: 16, name: "16万円" },
    { price: 17, name: "17万円" },
    { price: 18, name: "18万円" },
    { price: 19, name: "19万円" },
    { price: 20, name: "20万円" },
    { price: 25, name: "25万円" },
    { price: 30, name: "30万円" },
    { price: 35, name: "35万円" },
    { price: 40, name: "40万円" },
    { price: 45, name: "45万円" },
    { price: 50, name: "50万円" },
    { price: 60, name: "60万円" },
    { price: 70, name: "70万円" },
    { price: 80, name: "80万円" },
    { price: 90, name: "90万円" },
    { price: 100, name: "100万円" },
    { price: 110, name: "110万円" },
    { price: 120, name: "120万円" },
    { price: 130, name: "130万円" },
    { price: 140, name: "140万円" },
    { price: 150, name: "150万円" },
    { price: 160, name: "160万円" },
    { price: 170, name: "170万円" },
    { price: 180, name: "180万円" },
    { price: 190, name: "190万円" },
    { price: 200, name: "200万円" },
    { price: 250, name: "250万円" },
    { price: 300, name: "300万円" },
    { price: 350, name: "350万円" },
    { price: 400, name: "400万円" },
    { price: 450, name: "450万円" },
    { price: 500, name: "500万円" },
    { price: 600, name: "600万円" },
    { price: 700, name: "700万円" },
    { price: 800, name: "800万円" },
    { price: 900, name: "900万円" }
  ]
end

app/models/vehicle_type.rb
class VehicleType < ActiveHash::Base
  self.data = [
    { id: 1, name: '新車' },
    { id: 2, name: '未使用車' },
    { id: 3, name: '中古車' }
  ]

  include ActiveHash::Associations

  has_many :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :search_car, only: [:index, :search]

  def index
    if params[:car_name] != nil
      car_select = Car.where(manufacturer_id: params[:car_name])
      
      render json: {name: car_select}
    end
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      return redirect_to root_path
    end
    render :new
  end

  def search
    @searches = @q.result
  end

  private

  def car_params
    params.require(:car).permit(:name,
                                :price,
                                :manufacturer_id,
                                :grade,
                                :body_id,
                                :displacement,
                                :color,
                                :capacity,
                                :model_year,
                                :vehicle_type_id,
                                :mileage)
  end

  def search_car
    @q = Car.ransack(params[:q])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/index.html.erb
<%= link_to "車両登録", new_car_path %>

<%= search_form_for @q, url: search_cars_path do |f| %>
  <%= f.label :manufacturer_id_eq, 'メーカー' %>
  <br>
  <%= f.collection_select :manufacturer_id_eq, Manufacturer.all, :id, :name, {include_blank: "すべてのメーカー"}, {id: "car-select"} %>
  <%= f.collection_select :name_eq, [], :name, :name, {include_blank: "すべての車種"}, {id: "car-name"} %>
  
  <br>
  <%= f.label :price_gteq, '価格'%>
  <br>
  <%= f.collection_select :price_gteq, Price.all, :price, :name, {include_blank: "下限なし"}%>
  ～
  <%= f.collection_select :price_lteq, Price.all, :price, :name, {include_blank: "上限なし"}%>
  <br>
  <%= f.label :model_year_gteq, '年式'%>
  <br>
  <%= f.text_field :model_year_gteq, placeholder: "下限なし" %>
  ～
  <%= f.text_field :model_year_lteq, placeholder: "上限なし" %>
  <br>
  <%= f.label :mileage_gteq, '走行距離'%>
  <br>
  <%= f.collection_select :mileage_gteq, Mileage.all, :mileage, :name, {include_blank: "下限なし"}%>
  ～
  <%= f.collection_select :mileage_lteq, Mileage.all, :mileage, :name, {include_blank: "上限なし"}%>
  <br>
  <%= f.label :color_in, 'カラー'%>
  <br>
  <%= f.collection_check_boxes :color_in, Color.all, :color, :name, {}%>
  <br>
  <%= f.submit '検索' %>
<% end %>

<ul>
  <li><%= link_to "〜10万円", search_cars_path(q: {price_lteq: 10}) %></li>
  <li><%= link_to "〜30万円", search_cars_path(q: {price_lteq: 30}) %></li>
  <li><%= link_to "〜50万円", search_cars_path(q: {price_lteq: 50}) %></li>
  <li><%= link_to "〜70万円", search_cars_path(q: {price_lteq: 70}) %></li>
  <li><%= link_to "〜100万円", search_cars_path(q: {price_lteq: 100}) %></li>
  <li><%= link_to "〜150万円", search_cars_path(q: {price_lteq: 150}) %></li>
  <li><%= link_to "〜200万円", search_cars_path(q: {price_lteq: 200}) %></li>
  <li><%= link_to "〜250万円", search_cars_path(q: {price_lteq: 250}) %></li>
  <li><%= link_to "〜300万円", search_cars_path(q: {price_lteq: 300}) %></li>
  <li><%= link_to "300万円以上", search_cars_path(q: {price_gteq: 300}) %></li>
</ul>

app/views/cars/new.html.erb
<%= form_with model: @car, local: true do |f| %>
  <% if f.object.errors.any? %>
  <div class="error-alert">
    <ul>
      <% f.object.errors.full_messages.each do |message| %>
      <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <p>車両名</p>
  <%= f.text_field :name %>
  <p>価格</p>
  <%= f.text_field :price %>
  <p>メーカー</p>
  <%= f.collection_select(:manufacturer_id, Manufacturer.all, :id, :name, {include_blank: "---"}) %>
  <p>グレード</p>
  <%= f.text_field :grade %>
  <p>ボディ形状</p>
  <%= f.collection_select(:body_id, Body.all, :id, :name, {include_blank: "---"}) %>
  <p>排気量</p>
  <%= f.text_field :displacement %>
  <p>色</p>
  <%= f.text_field :color %>
  <p>定員</p>
  <%= f.text_field :capacity %>
  <p>年式</p>
  <%= f.text_field :model_year %>
  <p>車両種別</p>
  <%= f.collection_select(:vehicle_type_id, VehicleType.all, :id, :name, {include_blank: "---"}) %>
  <p>走行距離</p>
  <%= f.text_field :mileage %>

  <%= f.submit "登録する"%>
<% end %>

app/views/cars/search.html.erb
<%= search_form_for @q, url: search_cars_path do |f| %>
  <%= f.label :manufacturer_id_eq, 'メーカー' %>
  <br>
  <%= f.collection_select :manufacturer_id_eq, Manufacturer.all, :id, :name, {include_blank: "すべてのメーカー"}, {id: "car-select"} %>
  <%= f.collection_select :name_eq, [], :name, :name, {include_blank: "すべての車種"}, {id: "car-name"} %>
  <%# 絞り込み検索をするさいにグレードも検索できるようにする %>
  <br>
  <%= f.label :price_gteq, '価格'%>
  <br>
  <%= f.collection_select :price_gteq, Price.all, :price, :name, {include_blank: "下限なし"}%>
  ～
  <%= f.collection_select :price_lteq, Price.all, :price, :name, {include_blank: "上限なし"}%>
  <br>
  <%= f.label :model_year_gteq, '年式'%>
  <br>
  <%= f.text_field :model_year_gteq, placeholder: "下限なし" %>
  ～
  <%= f.text_field :model_year_lteq, placeholder: "上限なし" %>
  <br>
  <%= f.label :mileage_gteq, '走行距離'%>
  <br>
  <%= f.collection_select :mileage_gteq, Mileage.all, :mileage, :name, {include_blank: "下限なし"}%>
  ～
  <%= f.collection_select :mileage_lteq, Mileage.all, :mileage, :name, {include_blank: "上限なし"}%>
  <br>
  <%= f.label :color_in, 'カラー'%>
  <br>
  <%= f.collection_check_boxes :color_in, Color.all, :color, :name, {}%>
  <br>
  <%= f.submit '検索' %>
<% end %>

<% if @searches.present? %>
<div class="search-hit">
  <%= "#{@searches.length}件見つかりました。" %>
</div>
  <% @searches.each do |car| %>
  <div class="search-view">
    <div class="test">
      <%= car.name %>
      <%= car.price %>万円
      <%= car.manufacturer.name %>
      <%= car.grade %>
      <%= car.body.name %>
      <%= car.displacement %>cc
      <%= car.color %>
      <%= car.capacity %>人乗り
      <%= car.model_year %>年式
      <%= car.vehicle_type.name %>
      <%= car.mileage %>km
    </div>
  </div>
  <% end %>
<% else %>
  <div class="search-hit not-hit">検索結果が見つかりませんでした</div>
<% end %>

<%= link_to "トップページに戻る", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarAuction</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>